### ISSUE TITLE
Auxiliairies

### ISSUE THREAD

**Issue by mcandito** [bguil/UD-French-discussion#7]
(discussion Pise MCDM, SK, MC)
The only auxiliaries are "être", "avoir" and causative "faire"

All the modals "pouvoir", falloir etc.. are root and take a xcomp complement

Impact on treebanks:
modification to apply on French UD, cf. currently there remain other auxiliairies
A few do remain also in the sequoia treebank

**Comment by bguil** [comment]
This was already done in the dev version of UD_French-Sequoia:
 * Version 2.0 :  [388 cases](http://grew.loria.fr/search?custom=59e46c6d203c6&corpus=UD_French-Sequoia-2.0)
 * current dev version : [0 case](http://grew.loria.fr/search?custom=59e46c6d203c6&corpus=UD_sequoia-trunk)

This will be done for the next release of UD_French, version 2.1 (ongoing work)

**Comment by mcandito** [comment]
I remember now you told me that already

I close the issue then
